spring:
  ssl:
    bundle:
      jks:
        mq-tls-bundle:
          keystore:
            location: "/home/tdolby/github.com/ace-mq-tls-examples/generated-output/mqclient-p12/mqclient-plus-CA1.p12"
            password: "changeit"
            type: "PKCS12"
          truststore:
            location: "/home/tdolby/github.com/ace-mq-tls-examples/generated-output/mqclient-p12/mqclient-plus-CA1.p12"
            password: "changeit"
            type: "PKCS12"
