
# Local testing
#ibm.mq.queueManager=ACEv13_QM
#ibm.mq.channel=SYSTEM.BKR.CONFIG
#ibm.mq.connName=localhost(11003)

# Openshift QM
ibm.mq.queueManager=cp4iqm
ibm.mq.channel=MQ.CLIENT.SVRCONN
ibm.mq.connName=cp4iqm-ibm-mq-qm-cp4i.apps.openshift.yourcompany.com(443)

# Change the following lines as necessary. Set the ibm.mq.user 
# property to an empty string to send no authentication request.
ibm.mq.user=
#ibm.mq.password=passw0rd

ibm.mq.sslCipherSuite=TLS_AES_128_GCM_SHA256
ibm.mq.sslPeerName=CN=mqserver,OU=ExpertLabs,O=IBM,L=Minneapolis,ST=MN,C=US
ibm.mq.outboundSNI=HOSTNAME

# Deprecated as of mq-jms-spring-boot-starter 3.5.1 
#ibm.mq.jks.trustStore=/home/tdolby/github.com/ace-mq-tls-examples/generated-output/mqclient-p12/mqclient-plus-CA1.p12
#ibm.mq.jks.trustStorePassword=changeit
#ibm.mq.jks.keyStore=/home/tdolby/github.com/ace-mq-tls-examples/generated-output/mqclient-p12/mqclient-plus-CA1.p12
#ibm.mq.jks.keyStorePassword=changeit

# SSL bundles are the preferred mechanism
# Either of these will work - choice is driven by JKS/P12/PEM availability
#ibm.mq.sslBundle=mq-tls-jks-bundle
ibm.mq.sslBundle=mq-tls-pem-bundle
